feature/df 80 getbudgetbyparams
DoughFin/DoughFin_FE pull request #19
Opened 2024-02-10 19:02 UTC by trpubz

## Keypoints
- Add query file for BudgetsByParams
- Include budgets data into the app js
- Include budgetsbyparams in fetch call
- Error: export versus import of default
- Debug process, changed function input for const to variables for js
- Add category selection modal
- getBudgetByParams working on budget widet
- Get Budget Categories
- Remove caching on getBudgetCategories
- Float mutation is incorrect for incomes/expenses but connections are live
- Fix mutation amount to / 100

### Related Issue(s)
closes DF-80

### Checklist:
- [ ] New/Modified Tests are Passing
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings or errors.

#### Additional Notes:
Please enusre you pull to local, test localhost rails server and live server

2024-02-10 19:09 UTC, chisPmama approved these changes

2024-02-11 18:40 UTC, chisPmama commented on src/components/AddIncome/AddIncome.js
> +        amount: amountCents / 100,
This has an issue with being displayed on Transactions as $5.00 if the user actually wrote $500.00.

Could you look into this?

2024-02-11 18:42 UTC, chisPmama requested changes
Just one **hopefully** minor change. The AddIncome displays incorrectly in transactions.

2024-02-11 18:47 UTC, trpubz commented on src/components/AddIncome/AddIncome.js
> +        amount: amountCents / 100,
I'm not able to address this today...whoever coded the original logic might be able to lend some advice but there is certainly a disconnect between prop passing and the mutation/queries. This referenced line of code ensures the proper value is sent back through the mutation. Not sure if the issue is closer to data manipulation on the query (for transactions) or just on how it's displayed.

2024-02-12 16:32 UTC, MaryBruff requested changes

2024-02-12 16:32 UTC, MaryBruff commented on cypress/e2e/Dashboard.cy.js
This file seems to just contain the tests @josephlee702 wrote, any particular reason they've been copied from his branch and not left on the Cypress branch?
If you're going to add Cypress tests, make sure they test the component you built.

2024-02-12 16:32 UTC, MaryBruff commented on src/components/App/App.js
> +  localStorage.setItem('email', email);
This line can be removed since the localStorage object is not being retrieved anywhere and `email` is set in the line above.

2024-02-12 16:32 UTC, MaryBruff commented on src/components/App/App.js
> +  // const { budgetsData } = useGetBudgetsByParams(month, category, email);
Like all other useQuery hooks that retrieve data when the App mounts, the useGetBudgetByParams should follow the DDAU design convention.

2024-02-12 16:32 UTC, MaryBruff commented on src/components/Budget/BasicPie.js
> +  const isValidData = data && Array.isArray(data) && data.length > 0 && data.every(d => d.hasOwnProperty('value') && typeof d.value === 'number');
When the budgetData is properly drilled to this component, the chained conditionals can likely be reduced to something similar in the BarChart MUI component.

2024-02-12 16:32 UTC, MaryBruff commented on src/components/Budget/Budget.js
> +import React, { useState, useRef, useEffect, useMemo } from 'react'
Remove unused hook.

2024-02-12 16:32 UTC, MaryBruff commented on src/components/Budget/Budget.js
> +    const email = "moneybaggins@bigbanktakelilbank.doge";
This entire blocked dedicated to fetching budgets and budgetCategories should be be properly drilled through from App. Those states should not be set inside this child component.

2024-02-12 16:32 UTC, MaryBruff commented on src/components/Budget/Budget.js
> +    const toggleDropdownVisibility = () => {
Consider refactoring this to utilize a BasicSelect MUI component, there is no need to make these kinds of functions.

2024-02-12 16:32 UTC, MaryBruff commented on src/components/Budget/Budget.js
> +        };
The BasicSelect component will remove the need for EventListeners like this. VanillaJS in React is not maintainable/conventional

2024-02-12 16:32 UTC, MaryBruff commented on src/fetchCalls.js
No need to add anything new to this file, it's deprecated.

2024-02-12 16:32 UTC, MaryBruff commented on src/components/AddIncome/AddIncome.js
> +        amount: amountCents / 100,
Here's my thought. @trpubz your branch still does not appear have the correct `useCreateIncome` or `useCreateExpense` mutation that is on `main` and `main` seems to be functioning correctly updating state just not posting since the mutation merge yesterday.
<img width="885" alt="Screenshot 2024-02-11 at 12 35 02 PM" src="https://github.com/DoughFin/DoughFin_FE/assets/128327004/e0020ce1-bde3-4d42-9ff8-d3f3675c4534">
Here's how the FE app is handling floats for example with `totalIncome`:
The `getIncomes` hook fetches and returns the `income` as a float
<img width="541" alt="Screenshot 2024-02-11 at 12 36 40 PM" src="https://github.com/DoughFin/DoughFin_FE/assets/128327004/288c1924-bae2-4ee7-86d2-41a7d20d3679">
Then to avoid rounding errors, the `useEffect` handling setting `income` state coverts the float into a cents integer:
<img width="564" alt="Screenshot 2024-02-11 at 12 43 44 PM" src="https://github.com/DoughFin/DoughFin_FE/assets/128327004/99362790-5c74-4f11-922b-242228e31b86">
Then whenever any amount needs to be displayed in the App (income, expenses, transaction etc.) it's formatted into a USD currency string:
<img width="726" alt="Screenshot 2024-02-11 at 12 44 27 PM" src="https://github.com/DoughFin/DoughFin_FE/assets/128327004/86e8b2c6-4ece-4fa0-bd53-6c38dad3d7de">
This means we need to adhere to how floats are handled on `main`. 
A few more thoughts:
1. Pretty sure this is a bug, it's a matter of this branch not having parts of `main` like the `useMutation` fixes from Friday.
2. We are allowed to fix bugs, but this is a feature branch.
3. Lets leave this alone, I'm at a loss of words to be honest at this point..

2024-02-23 16:12 UTC, closed without merging

2024-02-23 16:12 UTC, josephlee702 commented
Was part of capstone pt.1 - closing.